syntax = "proto3";

option java_multiple_files = true;
option java_package = "spaceapp.linkshortener";
option java_outer_classname = "LinkServiceProto";

package link;

service LinkService {
  rpc GetShortLink (GetShortLinkRequest) returns (GetShortLinkResponse);
  rpc GetOriginalLink (GetOriginalLinkRequest) returns (GetOriginalLinkResponse);
}

message GetShortLinkRequest {
  string original_url = 1;
}

message GetShortLinkResponse {
  string short_url = 1;
}

message GetOriginalLinkRequest {
  string short_url = 1;
}

message GetOriginalLinkResponse {
  string original_url = 1;
}
